name: ESLint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Nodejs
          uses: actions/setup-node@v1
          with:
              node-version: "22.12.0"  

        - name: Install dependencies
          run: yarn install
          working-directory: .

        - name: Run ESLint
          run: yarn lint
          working-directory: .